// src/components/EventGroup.svelte
<script lang="ts">
import type {  DataGroup } from 'vis-timeline/esnext'
import { createEventDispatcher } from 'svelte'

export let group: DataGroup

const dispatch = createEventDispatcher()

function removeGroup() {
  dispatch('remove', group)
}

function updateGroup() {
  dispatch('update', group)
}

</script>

<div class="select-none flex" on:dblclick={updateGroup}>
  <span title="double click to edit" class="cursor-pointer">{group.content}</span>
  <button class="ml-2 rounded-full border w-6 h-6" on:click={removeGroup}>X</button>
</div>

// src/components/EventGroup.vue

<script lang="ts" setup>
import type { DataGroup } from 'vis-timeline/esnext'

interface Props {
  group: DataGroup
}

const props = defineProps<Props>()

const dispatch = defineEmits([
  'remove', 'update',
])
function removeGroup() {
  dispatch('remove', props.group)
}
function updateGroup() {
  dispatch('update', props.group)
}
</script>

<template>
  <div class="select-none flex" @dblclick="updateGroup">
    <span title="double click to edit" class="cursor-pointer">{{ group.content }}</span>
    <button class="ml-2 rounded-full border w-6 h-6" @click="removeGroup">
      X
    </button>
  </div>
</template>
